// display 

export const tempLogoAsciiArt = `
',:codxxdol:,'..........,:cloddxxxxxxxxxxxxxxxddddddddddoooooolllllllcccclllloooolcc:;,,'''',,,;;;;;;;;;;;,,,,''''..'..''''''',,,,,,,,;;;;;;;,,'''''''
,:lodxkkxdl:,'..........';:cloddddddddddddddddddddxxddddddddooolllllcccclloooooollc:;,,'''',,;:::cccccccc:::;;;,,,,''''....''',,,;;:::ccclllcc:::;;;;;
,:ldxkkkxdl:,''',,,;;,''',:clodddddddddddddddddddddddddddddddoolllccccccllllllllc::;,,'''',;;:ccllllllllcc::::;;;,,,''.....''',;::clloodddddddooolllll
,:ldxxdl:,,'.......''''''',,;clloodddddddddddddddddddddddddddooollcccccllllllccc::;;,,,,;;:cclloooddoollcc::;;;;;;;,,,''''',,;;:cloddxxxxkkkkkxxxxdddd
';cooc,'.....\s\s\s\s...............',;:cloooddddddddddxxxxddddddooooollllllllllllcc:::::::ccllooddddddddoolcc::::::::::::;;;,,;::clodxxkkkkkOOkkkkkkkkxxx
.,:oddol:;'...\s\s\s\s\s\s\s\s\s...............',;:clloooddddxdxxddddddddoooooooooooooollllllllooddddxxxxxxdddoollcccccccllllllccccccllodxxkkkkkkkkkkkkkkkkkkkk
.';ldxxxdol:;'.......\s\s\s\s\s\s\s\s\s\s..............',;:cllodddddxxxxxdddddddddddddddooooddddddxxxxxxxxxxxdddooollllooooooooooooooodddxxkkkkkkkkkkkkkkkkkkkkk
.':lodxxxdol:;'''''''''............................',;;:ccodddxxxxxxxxdddddddddddxxxxxxxxxxxxxxxxxxxdddddoooddddddddddddddddxxxxkkkkkkkkkkkkkkkkkkkkOO
';cldxkkkxdol:,'......'',,,;,'......................','''',;;::ccllllooodddddoooollllllllloooooddddxxxxxxxxxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkkkkOOOOOO
;cloxkkOkkxolc;'..........';ccc:;,''''''''''....................'''..'',,,,,,,,''''''.'''''''',,;;::clloddxxxxxxxxxxxxxxxxxxxkkkkkkkkkkkkkkkOOOOOOOOOO
cldxkkOOkkxdoc;,...........,:loddolc;;,,,,,,,,,;;;,''............................................''..''',;::clodxxxxxxxxxxxkkkkkkkkkkkkOOOOOOOOOOOOkkk
odxkkOOOkkxdol:,'..........,:lodxxxxdolc;,,,,''',,,;:::;,'................\s\s\s......................''...'''','',;clodxxxxkkkkkkkkkkkkkkkkkkkkkkkkkxxdd
dxkkOOOOkkkxdlc:,..........':codxxxxxxxxdoc:;,,,'''''',;::c:;,'...\s\s\s........\s\s\s\s........................'',;,,''''',:lodxxxxxxkkkkkkxxxxxxdddddddoolc
xkOOOOOOOkkxdolc;'.........,:codxxxxxxxxxkxdol:;;;,,'''''',,;:cc:;,..\s\s\s\s...\s..\s\s\s\s.......'''.............''','''''....,;clodddddxxdddooolllcccccc::;;
kOOOOOOOOkkkxdol:,'........,:lodxxkxkxkkkkkkkkxoc:;;;;,,'''''',,;::c:;'.\s\s\s\s\s\s\s..\s\s\s.........................'''..'.......';:llloolllc::;;,,,,,,,,,,,,
kOOOOOOOOOkkxdolc;'........,:lodxxxxxxxxxxkkkkkkxdl:,,;;;,,,''''',,,;:c:;'..\s\s\s\s\s...\s\s\s......................................',:::;;,,''......'',,,,,,
OOOOOOOOOOkkxxdlc;,........,:lodxxxxxxxxxxxxxkkkkkkxo:,',;;;;,,,'''',,,;:c::;..\s\s\s..\s\s\s\s\s\s\s\s\s...................................,,,,'''.....''',,,,,,,
OOOOOOOOOOkkxdolc;'........,:lodxxxxxxxxxxxxkkkkkkkkkxo:,.',;::;;,,,,,,,,,;:::;'.\s\s..\s\s\s\s\s\s\s\s\s\s\s\s\s\s.............................';::;;;;,,,''',,,;;;,,
OOOOOOOOOkkkxdol:;'.......',:codxxxkkxxxxkkkkkkkkkkkkkkkdl,...,;::::;;,,,,;;;;::,.\s.....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s........\s\s\s\s\s\s........,cooolc:::;;,,',,,,,,,,,
OOOOOOOOkkkkxdol:,'.......',:clodxxxxxkkkkkkkkkkkkkkkkkkkkdl,....';::c:::::;;;::;'.\s\s....\s\s\s\s\s\s\s\s\s\s\s\s\s\s........\s\s\s\s\s\s\s\s......,ldxxkxdlc::;;,,,,,,,,,,,
OOOOOOOkkkkkxdolc;'........';clodxkkkkkkkkkkkkkkkkkkkkkkkkkxdc'......',;::ccccc:;,..\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s....,cooddxxxdlc:;,,,,,,',,,,,
OOOOOOOkkkkkkxdoc:,'.......';clodxkkkkkkkkkkkkkkkkkkkkkkkkkkxxl;.............'''....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s...;oooooddddol:;,,,'''''',,,
OOOOOOOOkkkkkxdol:;'.......';:lodxkkkkkkkkkkkkkkkkkkkkkkkkxxxxxo:'.......\s\s.\s\s...\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s..;llloooddddoc:;,'''''',,,,
OOOOOOOOkkkkkxdolc;'........,:lodxkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxdc,..............\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s...\s\s\s..,cccllodddxdo:;'''''',,;;;
OOOOOOOOkkkkkkxdlc;,'.......,:lodxkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxdo;........\s\s..\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s..,cllllooddxxl;,''''',,;;;:
OOOOOOOOOOOkkkxdoc:,'.......';codxkkkkkkkkkkkkkkkkkkkkkkkkxxxxxxxxxo:'.........\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s..\s\s\s..'clcllooddxxl;,'''',,;;;::
OOOOOOOOOOOkkkxdol:;'.......';cldxxkkkOOOOOkkkkkkkkkkkkkkkkkkxxxxxxxdc'......\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s.\s\s...;ccclloddxxo;'''',,,;;;::
OOOOOOOOOOOkkkxxolc;'........';codxkkOOOOOOOOkkkkkkkkkkkkkkkkkxxxxxxxdc,....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s...';:ccloodxxo;''',,,;;;;::
OOOOOOOOOOOOkkkxdlc;,.........,:codxkkkkkOOkkkkkkkkkkkkkkkkkxxxxxxxxxxdc,.....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s....;:cclloodxo:,,,,,;;;;:::
OOOOOOOOOOOOkkkxolc;,..........,;clodxxkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxdl,.....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s....,::cclodddo:,',,;;;;;:::
OOOOOOOOkkkkkkxxolc;'...........',:clodddxxxxxxxxxxxxxxxxxxxxxxxxxdddddddl,'....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s......,:cclllolllc,',,,;;;;:::
OOkkOOkkkkkkkkxdol:;'.............,;cllooooddddddxxxxxxxxxxxddddddddddddxdl:,.....\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s..\s\s\s........':cclllc:col;',,,;;;;;;;
kkkkkkkkkkkkkkxdol:;'.............',;:cccllllooooddddddddddddddddddddddxxxddc,.......\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s....\s\s..\s\s...';cclc:;:loo:'',,,;;;;;,
kkkkkkkkkkkkkkxdol:;'..........'',,;;::::::::ccllooodddddddddddddddddxxxxxxxd:'.........\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s............';:ccc;;:clloc,''',,,,,,,
kkkkkkkkkkkkkkxdol:;'.....',,,,;;;::::;;,,,,;;::ccllloooddddxxxxxxxxxxxxxxxxxl,'..........\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s.\s\s\s\s\s\s\s\s..........':cc:;,,;:clool,.'''''''''
xkkkkkkkkkkkkkxxolc;,'''',;:::::::::;;,''''''''',,;::clllooddxxxxxxxxxxxxxxxxl;''.............\s\s\s\s\s\s\s\s\s\s\s.................';::;,'',;;::clll;''',,,,,,,
ddxxxxkkkkkkkkxxolc:;,,,;;::ccccc::;,''............',,;::clloodddxxxxxxxxxxxdl;,'................\s\s\s\s\s\s\s\s\s\s............',::;,'.',;;;;:::cllc:::::ccccc
clooddxxxxxxxxddolc:;,,,;;:::ccc::;;,'.................'',;::clloooddxxxxdddddl;'...................\s\s\s\s\s.......''',,,,,''...',;;;;;::::cccllooooddddd
,;:ccloodddddoolcc:;;;,;;;;;::::::;;,,''....................',,;::cllodddddddoc;'.....''......................'''........'',,;;;;;:::::::cclddxxxxxxxx
'',,;:clloooolcc:::;;;;;;::::::::::::;;;,,,'''''.................',;clooodddo:''..'''''''''............'.....''''',,,,,,,;;;;;;;;;::::::ccccodxxxxkkkk
'',,;;:ccllllc::::::::ccccllllllllllllcccc::::;;;;;;;,,,,,,'''...',;looooc:;;''''''''',,,,,,,,,,,,,,,,;;;,,,,,;::ccccccc::::::::::::::::::cclodddddddd
;;;;::cccllcc:::::cclllooodddddddddddoooooolllllllllllllccccc:::::coolllc:;;,,'''''',,;::cc::::c:::::::::ccc;'',,;;;;;:::;:;;;::;:::;;;;;;;;:loooooooo
::ccccccccccccccclloddddxxxxxxxxxxxxxxxxxddddddddddddddddddddoolcccllloolc;;,,''',,;::cllllllllllllllcccllllc:;;,'..',,,,,;;;;;;;;;;,,,,'',,;coooooooo
ccclllllllllllllloddxxxxxkkkkkkkkkkkkkkxxxxxxxxxxxxxxxxxxxxxdlcloodddddol:;;,,,,,;:clllooooooollllllllllllloloolc:;;''...',,;;;;,,,;,,,,',,,,cdddddddd
llllooooooooooddddxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdlcloxxxxxxddlc:;;,,;;:ccloooddddoooooollllllllllllllooodoc;,'...,;;;;;;,,,,,,,;,',cxxxxxxxx
odddddddxxxxxxxxxxkkkkkkkkkkkkkkOOOOOOkkkkkkkkkkkkkOOOOkxoloxxkkxxxxxdolc:;;;;:cllodddddddddddooooooooolllllolllloooooolc;',;;;;;;;;;,,,,;,,;cxkkkkkkk
xxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOOOxdddkkkkkkkkxxxdlc::::::cooddxxxxxdddddddddddoddoooooooooooooooodddolc;,',;;;;;;;;;;;,;cxOkkkkkk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOOkddkOOOOOkkkkkxxdolcccclloddxxxxxxxxxxxxxddddddddddddddddddddddddodddddddl:,'.',,;:::;;,;cxkkkkkkk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOOOOOkkkkOkkdoxO0000OOOOkkkxxdollllooddxxxxxxxxxxxxxxxxxxxxxxxdddddddxxxxxxxxxxdddddddddolc,''',,;;;;,:dkkkkkkk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkdllk00000000OOOOkxxdooooodddxxxxxxxkkkkkkkxxxkkxxxxxxxxxxxxxxxxxxkkkkkxxddddddddddl:'...',;;;lxkkkkkk
kkkkkkkkkkxxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxl:lOKKKKKKK000OOOkxxdddoddddxxxxkkkkkkkkkkkkkkkkkkkkkkkxxkkxxxxxxxkxxxkkxxxddddddddddl;....',,:dxxxxxx
kkkkkkkkkkkxxxxkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxo::dO0KKKKKKK0000OOkxddddddxxxxxxkkkkOOOOkkkkkkkkkkkkkkkkkkkkkxxxxxkkkxxxxxxxdxxxddddddddc,.\s..';ldxxxxx
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkxl;cdOKKKKKXXXKK0000OkddooddxxxxxkkkkkOOkOOOOkkkkkkkkkkkkkkkkkkkxxxkkkkkkkxxxxxdxxxdddddddddl,.\s\s..;oddddd
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkd:;cxO0KKKKKKKKKKKKKKOkddoodxxxkkkkkOOkOOOkOOkkkkkkkkkkkkkkkkkxxkkkxxxkkkkxxxxxxdddxxxdodddoool;.\s\s..;ldddd
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkOOOOOkkkxl,,cxO00000KKKKKKKKKK0OxdoodxkkkkkkkkOOOOOOkkOkkkkkkxxkkxxxxxxxxxxxxxxxxxxxddxxxddddxxxddodoooolc;..\s\s.,lodd
dddddddddddddddddddddddddxxxxxxxxxxxxdddo:'':odxxxxkkkkkkkkOOkkxdolloodddddddxdxxxxxxxddddooooooooooooooooooooooooooooloolllllllollllllccc::,.\s\s\s.':ll
........................'''''''''''............'''''''''''''''''..............''''..''.........................................................\s\s\s....
`;

export const logoArt = `
cdo;...';ldddddddddoolcllllc;,,:clc:;,,''',:clolcc|\n
:oc'......',;clloddddoooollcclodddocccc:::ldxkkkkx|\n
:dxl,..........',;::ccllllllllllooooddddddxkkkkkkO|\n
dkkd:'..'cllc;,''''.............',,;:cloxxkkkkkkkx|\n
kOkxl,..'cdxxxoc;,,,,''..\s\s\s........''',;clolc::::|\n
OOOko;..'cdxxxkkxl:,,,;,,'....\s\s..........,:;,'',,|\n
OOkko;..'cdxkkkkkkxl;'',,;,..\s\s\s\s\s\s\s\s\s\s\s..cooc;,,,|\n
OOkkd:'.':dkkkkkkkkxo;......\s\s\s\s\s\s\s\s\s\s\s\s.'codl;',,|\n
OOOkxc,..;okkkkkkkkkxdc'..\s\s\s\s\s\s\s\s\s\s\s\s\s\s\s.:ldo;,,;|\n
OOOkxl,..':oxkkkkkkxxxdc'..\s\s\s\s\s\s\s\s\s\s\s\s\s\s.,col;,;;|\n
kkkkxl,...';clooddxxddxdc;'.\s\s\s\s\s\s\s\s\s\s\s...,ccc:,,;|\n
xkkkxl,',;;;,,,;:coddxxxdl;....\s\s\s\s\s\s....',;:c:;,,|\n
coddoc;;:::;,'....';:codol:'...........',,,;::clod|\n
;:llcccllooolcc::::;;:ll:;,',;;;;;;;;,,;;;;;;;:ldd|\n
llooodxxkkkkkxxxxxxdoddl:;;:looolllllc:;,,;;,,,cdx|\n
xxkkkkkkkkkOOOOOkkkkkkdlcllddxdddddooddool:;,;;lxk|\n
kkkkkkkkkkkkkkkxxO00Okdoddxkkkkkkxxxxxxxxddoc,':dx|\n
kkkkkkkkkkkkkxodOKKK0kdxxkkOOkkkkkkkxxxxxxxddl,.:o|\n
ooooooodddddoc:oxxkkxoloodddddoooollllllllllcc;..;|\n
`;