export const members_2023 = [
  {
    id: 1,
    name: "Abhishek Kumar",
    position: "President",
    github: "https://github.com/AmrealAbhishek",
    linkedin: "https://www.linkedin.com/in/abhishek-kumar-284849215/",
    instagram: "https://www.instagram.com/amrealabhishek/",
    email: "AmrealAbhishek@gmail.com",
  },
  {
    id: 2,
    name: "Animesh Rai ",
    position: "Technical Head",
    github: "https://github.com/ar005",
    linkedin: "https://www.linkedin.com/in/animesh-rai-a9802b244/",
    instagram: "https://www.instagram.com/_ar025",
    email: "raianimeshldon0802@gmail.com",
  },
  {
    id: 3,

    name: "Rahul Vijayakumar",
    position: "Technical Co-Head",
    github: "https://github.com/rahulvk007",
    linkedin: "https://www.linkedin.com/in/rahul-vk8244/",
    instagram: "https://www.instagram.com/rahul.vk007/",
    email: "rahulptvijayakumar@gmail.com",
  },
  {
    id: 4,
    name: "Dhananjay Chauhan",
    position: "Frontend Lead",
    github: "https://github.com/Dhananjay-Chauhan",
    linkedin: "#",
    instagram: "#",
    email: "#",
  },
  {
    id: 5,
    name: "Kartikey Subramanium",
    position: "Cybersecurity Head",
    github: "github.com/hellokartikey",
    linkedin: "#",
    instagram: "instagram.com/kartikey_2811",
    email: "kartikey@tutanota.com",
  },
  {
    id: 6,
    name: "Aditi Rai",
    position: "Competitive Programming Lead",
    github: "https://github.com/AditiRai17",
    linkedin: "https://www.linkedin.com/in/aditi-rai-507528221/",
    instagram: "https://www.instagram.com/noveworld/",
    email: "raiaditi178@gmail.com",
  },
  {
    id: 7,
    name: "Venukanthan BS",
    position: "Cyber Security Lead",
    github: "https://github.com/itsvenu22",
    linkedin: "https://www.linkedin.com/in/venukanthan/",
    instagram: "https://www.instagram.com/itsvenu22/",
    email: "venukanthan.bs2021@vitstudent.ac.in",
  },
  {
    id: 8,
    name: "Dhruv Hatkar",
    position: "OS Lead",
    github: "https://github.com/slipstream8125",
    linkedin: "http://www.linkedin.com/in/dhruv-hatkar",
    instagram: "https://instagram.com/hatkar04_dhruv",
    email: "hatkardhruv@gmail.com",
  },

  {
    id: 9,
    name: "Meetesh Saini",
    position: "Backend Lead",
    github: "https://github.com/Meetesh-Saini",
    linkedin: "https://www.linkedin.com/in/meetesh-saini-5a3218244",
    instagram: "#",
    email: "code.meeteshsaini@gmail.com",
  },
  {
    id: 10,
    name: "Hrishikesh Naramparambath",
    position: "Media Head",
    github: "https://github.com/kingslayer1312",
    linkedin:
      "https://www.linkedin.com/in/hrishikesh-naramparambath-24b010222/",
    instagram: "https://www.instagram.com/quitepossiblyhrishi",
    email: "hrishabari@gmail.com",
  },
  {
    id: 11,
    name: "Kathir.M.N",
    position: "Media Co-Head",
    github: "https://github.com/kathirmn",
    linkedin: "https://www.linkedin.com/in/kathirmn/",
    instagram: "https://www.instagram.com/kathir_m_n/",
    email: "mnkathir2004@gmail.com",
  },
  {
    id: 12,
    name: "Mogesh S G",
    position: "Media Advisory",
    github: "https://github.com/mogesh06",
    linkedin: "www.linkedin.com/in/mogeshvar-s-g",
    instagram: "https://www.instagram.com/_.mogesh06._",
    email: "mogesh03@outlook.com",
  },
  {
    id: 13,
    name: " Srideep Aalla ",
    position: "Operations head ",
    github: "https://github.com/Srideepaalla",
    linkedin:
      "https://www.linkedin.com/in/srideep-aalla-357005267?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    instagram: "https://www.instagram.com/srideepaalla?igsh=cGI4djZ6ZDQ4c2R4",
    email: "srideep7.sa@gmail.com",
  },

  {
    id: 14,
    name: " K Revanth Sai",
    position: "Management Treasury ",
    github: "https://github.com/Revanthsai2003",
    linkedin: "https://www.linkedin.com/in/revanth-sai-9a8240231/",
    instagram: "https://www.instagram.com/k_revanth_sai/",
    email: "revanthsai.k2021@vitstudent.ac.in",
  },
];
