export const members_2024 = [
  {
    id: 1,
    name: "Ojass Pravin Bharati",
    position: "President",
    github: "https://github.com/WizzyGeek",
    linkedin: "https://www.linkedin.com/in/ojass-bharati-ba8a48124",
    instagram: "https://www.instagram.com/bharatiojass/",
    email: "mailto:ojasscoding@gmail.com",
  },
  {
    id: 2,
    name: "Shaina",
    position: "Vice President",
    github: "#",
    linkedin: "https://www.linkedin.com/in/shaina05",
    instagram: "https://www.instagram.com/shainaofficia1",
    email: "mailto:shainaofficia10@gmail.com",
  },
  {
    id: 3,
    name: "Aadivishnu Gajendra",
    position: "Technical Lead",
    github: "https://github.com/mradigen",
    linkedin: "https://linkedin.com/in/aadivishnu-gajendra",
    instagram: "https://instagram.com/lugvitc",
    email: "mailto:aadivishnu@proton.me",
  },
  {
    id: 4,
    name: "Siya Kumar",
    position: "Content Lead",
    github: "https://github.com/siya21k",
    linkedin: "https://www.instagram.com/siyaa.k21/",
    instagram: "http://www.linkedin.com/in/siyakumar",
    email: "mailto:siyak.kumar21@gmail.com",
  },
  {
    id: 5,
    name: "Harshanth Srinivasan",
    position: "Media Lead",
    github: "https://github.com/thebluedev",
    linkedin: "https://www.linkedin.com/in/harshanth-srinivasan-9a125a252/",
    instagram: "https://instagram.com/harshanthhhh/",
    email: "mailto:harshanthsrinivasan@gmail.com",
  },
  {
    id: 6,
    name: "S.Keerthana",
    position: "Outreach Lead",
    github: "#",
    linkedin: "https://www.linkedin.com/in/keerthana-sundar-40ba52277/",
    instagram: "https://www.instagram.com/___ketzzz/",
    email: "mailto:keerthana.s2022c@vitstudent.ac.in",
  },
  {
    id: 7,
    name: "Shyam Sundar R",
    position: "Treasurer",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "#",
  },
  {
    id: 8,
    name: "Niket Girdhar",
    position: "Management Lead",
    github: "https://github.com/lugvitc",
    linkedin: "https://www.linkedin.com/in/niket-girdhar-068858250/",
    instagram: "https://instagram.com/lugvitc",
    email: "mailto:cclinuxclub@vit.ac.in",
  },
  {
    id: 9,
    name: "Vivek Chaudhary",
    position: "Co-Management Lead",
    github: "https://github.com/Vivek084c",
    linkedin: "https://www.linkedin.com/in/vivek-chaudhary-8243a9250/",
    instagram: "https://instagram.com/lugvitc",
    email: "mailto:cclinuxclub@vit.ac.in",
  },
];