export const members_2024 = [
  {
    id: 1,
    name: "Ojass Pravin Bharati",
    position: "President",
    github: "https://github.com/WizzyGeek",
    linkedin: "https://www.linkedin.com/in/ojass-bharati-ba8a48124",
    instagram: "https://www.instagram.com/bharatiojass/",
    email: "mailto:ojasscoding@gmail.com",
  },
  {
    id: 2,
    name: "Shaina",
    position: "Vice President",
    github: "#",
    linkedin: "https://www.linkedin.com/in/shaina05",
    instagram: "https://www.instagram.com/shainaofficia1",
    email: "mailto:shainaofficia10@gmail.com",
  },
  {
    id: 3,
    name: "Yeyati Prashar",
    position: "Technical Lead",
    github: "https://github.com/Blacksword66",
    linkedin: "https://www.linkedin.com/in/yeyati-prasher-b5981127a/",
    instagram: "https://instagram.com/lugvitc",
    email: "mailto:yeyatiprasher@gmail.com",
  },
  {
    id: 4,
    name: "Shyam Sundar R",
    position: "Treasurer",
    github: "#", 
    linkedin: "http://www.linkedin.com/in/shyamsundar-r",
    instagram: "https://www.instagram.com/__shyam.sundar__/profilecard/",
    email: "ssr83432@gmail.com",
  },
  {
    id: 5,
    name: "Harshanth Srinivasan",
    position: "Media Lead",
    github: "https://github.com/thebluedev",
    linkedin: "https://www.linkedin.com/in/harshanth-srinivasan-9a125a252/",
    instagram: "https://instagram.com/harshanthhhh/",
    email: "mailto:harshanthsrinivasan@gmail.com",
  },
  {
    id: 6,
    name: "S.Keerthana",
    position: "Outreach Lead",
    github: "#",
    linkedin: "https://www.linkedin.com/in/keerthana-sundar-40ba52277/",
    instagram: "https://www.instagram.com/___ketzzz/",
    email: "mailto:keerthana.s2022c@vitstudent.ac.in",
  },
  { 
    id: 7,
    name: "Siya Kumar",
    position: "Content Lead",
    github: "https://github.com/siya21k",
    linkedin: "https://www.instagram.com/siyaa.k21/",
    instagram: "http://www.linkedin.com/in/siyakumar",
    email: "mailto:siyak.kumar21@gmail.com",
    
  },
  {
    id: 8,
    name: "Vivek Chaudhary",
    position: "Management Lead",
    github: "https://github.com/Vivek084c",
    linkedin: "https://www.linkedin.com/in/vivek-chaudhary-8243a9250/",
    instagram: "https://instagram.com/vivek_084",
    email: "mailto:vivek.choudhry2022@vitstudent.ac.in",
  },
  {
    id: 9,
    name: "Mogesh S G",
    position: "Media Advisory",                           
    github: "https://github.com/mogesh06",
    linkedin: "www.linkedin.com/in/mogeshvar-s-g",
    instagram: "https://www.instagram.com/_.mogesh06._",
    email: "mogesh03@outlook.com",
  },
  {
    id: 10,
    name: "Riya Bansal",
    position: "Advisory",    // get data from anumeya
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "#",
  },
  // {
  //   id: 9,
  //   name: "Niket Girdhar",
  //   position: "Ex-Management Lead",
  //   github: "https://github.com/NiketGirdhar22",
  //   linkedin: "https://www.linkedin.com/in/niket-girdhar-068858250/",
  //   instagram: "https://www.instagram.com/niketgirdhar",
  //   email: "mailto:niketgirdhar2004@gmail.com",
  // },
  // {
  //   id: 10,
  //   name: "Aadivishnu Gajendra",
  //   position: "Ex-Technical Lead",
  //   github: "https://github.com/mradigen",
  //   linkedin: "https://linkedin.com/in/aadivishnu-gajendra",
  //   instagram: "https://instagram.com/lugvitc",
  //   email: "mailto:aadivishnu@proton.me",
  // },
];
