export const members_2024 = [
  {
    id: 1,
    name: "Ojass Pravin Bharati",
    position: "President",
    github: "https://github.com/WizzyGeek",
    linkedin: "https://www.linkedin.com/in/ojass-bharati-ba8a48124",
    instagram: "https://www.instagram.com/bharatiojass/",
    email: "mailto:ojasscoding@gmail.com",
  },
  {
    id: 2,
    name: "Shaina",
    position: "Vice President",
    github: "#",
    linkedin: "https://www.linkedin.com/in/shaina05",
    instagram: "https://www.instagram.com/shainaofficia1",
    email: "mailto:shainaofficia10@gmail.com",
  },
  {
    id: 3,
    name: "Aadivishnu Gajendra",
    position: "Technical Lead",
    github: "https://github.com/mradigen",
    linkedin: "https://linkedin.com/in/aadivishnu-gajendra",
    instagram: "#",
    email: "#",
  },
  {
    id: 4,
    name: "Siya Kumar",
    position: "Content Lead",
    github: "https://github.com/siya21k",
    linkedin: "https://www.instagram.com/siyaa.k21/",
    instagram: "http://www.linkedin.com/in/siyakumar",
    email: "mailto:siyak.kumar21@gmail.com",
  },
  {
    id: 5,
    name: "Harshanth Srinivasan",
    position: "Media Lead",
    github: "https://github.com/thebluedev",
    linkedin: "https://www.linkedin.com/in/harshanth-srinivasan-9a125a252/",
    instagram: "https://instagram.com/harshanthhhh/",
    email: "mailto:harshanthsrinivasan@gmail.com",
  },
  {
    id: 6,
    name: "Keerthana S",
    position: "Outreach Lead",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "#",
  },
  {
    id: 7,
    name: "Shyam Sundar R",
    position: "Treasurer",
    github: "#",
    linkedin: "#",
    instagram: "#",
    email: "#",
  }
];