export const members_2025 = [
  {
    id: 1,
    name: "Dharmik Vivek Shinde",
    position: "Chairperson",
    github: "https://github.com/iamdmix",
    linkedin: "https://www.linkedin.com/in/dharmik-vivek-shinde-891156282",
    instagram: "https://www.instagram.com/shindedharmik",
    email: "mailto:dharmikvivek.shinde2023@vitstudent.ac.in",
  },
  {
    id: 2,
    name: "Anumeya Sehgal",
    position: "General Secretary",
    github: "https://github.com/KreativeThinker",
    linkedin: "https://www.linkedin.com/in/anumeya-sehgal",
    instagram: "https://www.instagram.com/kreative.thinker",
    email: "mailto:anumeyasehgal@proton.me",
  },
  {
    id: 3,
    name: "Adhya Sharma",
    position: "Joint secretary",
    github: "https://github.com/Adhya2508",
    linkedin: "https://www.linkedin.com/in/adhya-sharma-94903528b",
    instagram: "https://www.instagram.com/adidabest_2508",
    email: "mailto:adhyasharma250805@gmail.com",
  },
  {
    id: 4,
    name: "Naveen",
    position: "Treasurer",
    github: "https://github.com/magarmach-hash",
    linkedin: "https://www.linkedin.com/in/naveen-mr-a5301a28b",
    instagram: "https://www.instagram.com/naveentinkercad",
    email: "mailto:naveentinkercad@gmail.com",
  },
  {
    id: 5,
    name: "Siddharth Karanam",
    position: "Technical Lead",
    github: "https://github.com/nots1dd",
    linkedin: "https://www.linkedin.com/in/siddharth-karanam",
    instagram: "https://www.instagram.com/sidkaranam05",
    email: "mailto:sid9.karanam@gmail.com",
  },
  {
    id: 6,
    name: "Omkar Rajurkar",
    position: "Management Lead",
    github: "https://github.com/omkar785",
    linkedin: "https://www.linkedin.com/in/omkar-rajurkar",
    instagram: "https://www.instagram.com/_omkar_785",
    email: "mailto:omkar.rajurkar7@gmail.com",
  },
  {
    id: 7,
    name: "Shrreya Vishwanathan",
    position: "Management Lead",
    github: "https://github.com/shrreyvish",
    linkedin: "https://www.linkedin.com/in/shrreya-vishwanathan-29222228b",
    instagram: "https://www.instagram.com/shrrey_vish",
    email: "mailto:shrreyavishwanathan@gmail.com",
  },
  {
    id: 8,
    name: "Rejit Antony",
    position: "Media Lead",
    github: "https://github.com/dreamgamer5000",
    linkedin: "https://www.linkedin.com/in/rejitantony0903/",
    instagram: "https://www.instagram.com/dreamgamer5000",
    email: "mailto:antonyrejit@gmail.com",
  },
  {
    id: 9,
    name: "Atharv Shiva Hiremath",
    position: "Social Media Lead",
    github: "https://github.com/atharvhiremath",
    linkedin: "https://www.linkedin.com/atharv-hiremath",
    instagram: "https://www.instagram.com/atharv.hiremath",
    email: "mailto:y2005atharv@gmail.com",
  },
  {
    id: 10,
    name: "Tiya Sur",
    position: "Content Lead",
    github: "https://github.com/tia2905",
    linkedin: "https://www.linkedin.com/in/tiya-sur-1346352a7",
    instagram: "https://www.instagram.com/teaaa_s_2",
    email: "mailto:tiyasur28@gmail.com",
  },
];
