export const members_2026 = [
  {
    id: 1,
    name: "Amiitesh TSP",
    position: "Chairperson",
    github: "https://GitHub.com/embeddingbits",
    linkedin: "https://www.linkedin.com/in/amiitesh-pradeep-kumar-582bb831a",
    instagram: "https://www.instagram.com/tspamiitesh",
  },
  {
    id: 2,
    name: "Atri Mukherjee",
    position: "Vice Chairperson",
    github: "https://github.com/rade-ark",
    linkedin: "https://www.linkedin.com/in/atri-mukherjee-6b66b7306",
    instagram: "https://www.instagram.com/awayshark",
  },
  {
    id: 3,
    name: "Kashyap M P",
    position: "General Secretary",
    github: "https://github.com/6kashy",
    linkedin: "https://www.linkedin.com/in/kashyap-m-p-a3b22b32a/",
    instagram: "https://www.instagram.com/6kashy/",
  },
  {
    id: 4,
    name: "Karthik Ramanathan Lakshmanan",
    position: "Joint Secretary",
    github: "https://github.com/karthik20066002/",
    linkedin: "https://www.linkedin.com/in/axissprime/",
    instagram: "",
  },
  {
    id: 5,
    name: "Atharava Srivastava",
    position: "Treasurer",
    github: "https://github.com/AtharavaSrivastava",
    linkedin: "https://www.linkedin.com/in/atharava-srivastava-552375387",
    instagram: "https://www.instagram.com/bob_umushay",
  },
  {
    id: 6,
    name: "Aadhithya Narayanan Madhusudhanan",
    position: "Technical Lead",
    github: "https://github.com/derpitron",
    linkedin: "https://www.linkedin.com/in/b328dy67ss53a69b321/",
    instagram: "https://www.instagram.com/aadhitya281/",
  },
  {
    id: 7,
    name: "Kavin Karthik",
    position: "Design & Media Lead",
    github: "https://github.com/Krypton-KK",
    linkedin: "https://linkedin.com/in/a-kavin-karthik",
    instagram: "https://www.instagram.com/krypton.kk",
  },
  {
    id: 8,
    name: "Shamant Marathe",
    position: "Management Lead",
    github: "https://www.github.com/i-m-sham",
    linkedin: "https://www.linkedin.com/in/shamant-marathe-9b88a4323",
    instagram: "",
  },
];
